export interface Product {
  id: string;
  name: string;
  slug: string;
  price: number;
  salePrice?: number;
  images: string[];
  category: string;
  collection: string;
  description: string;
  material: string;
  inStock: boolean;
  isNew: boolean;
  isBestSeller: boolean;
  availableSizes: string[];
  availableShapes: string[];
  availableLengths: string[];
  processingTime: string;
  tags: string[];
  rating: number;
  reviewCount: number;
}

export const SIZES = ['XS', 'S', 'M', 'L', 'XL', 'Custom Size'];
export const SHAPES = ['Square', 'Rounded Square', 'Round', 'Oval', 'Almond', 'Stiletto', 'Coffin'];
export const LENGTHS = ['Short', 'Medium', 'Long', 'Extra Long'];

export const COLLECTIONS = [
  { id: 'all', label: 'All Collections' },
  { id: 'french-classic', label: 'French & Classic' },
  { id: 'glitter-metallic', label: 'Glitter & Metallic' },
  { id: 'nail-art', label: 'Nail Art' },
  { id: 'solid-colors', label: 'Solid Colors' },
  { id: 'custom', label: 'Custom' },
];

export const DISCOUNT_CODES: Record<string, number> = {
  SILVER14: 0.1,
  WELCOME15: 0.15,
  EU20: 0.2,
};

export const products: Product[] = [
  {
    id: '1',
    name: 'Pink Muse',
    slug: 'pink-muse',
    price: 48,
    images: [
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image1.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image2.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image3.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image4.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image5.jpg',
      '/images/InstructionGuide/image1.jpg',
      '/images/InstructionGuide/image2.jpg',
      '/images/InstructionGuide/image3.jpg',
      '/images/InstructionGuide/image4.jpg',
      '/images/InstructionGuide/image5.jpg',
    ],
    category: 'cute',
    collection: 'Dễ thương',
    description:
      'Pink Muse is an artistic press-on nail set featuring dreamy pink tones, standout 3D details, and metallic accents. Blending dollcore aesthetics with high-fashion style, it creates a unique and eye-catching look.',
    material: 'Premium ABS acrylic with gel topcoat',
    inStock: true,
    isNew: true,
    isBestSeller: false,
    availableSizes: SIZES,
    availableShapes: ['Square', 'Rounded Square', 'Oval', 'Almond', 'Coffin'],
    availableLengths: ['Short', 'Medium', 'Long'],
    processingTime: '3-5 business days',
    tags: ['pink', 'cute', 'dollcore', '3d', 'metallic'],
    rating: 4.9,
    reviewCount: 214,
  },
  {
    id: '2',
    name: 'Monkey Sundae',
    slug: 'monkey-sundae',
    price: 50,
    images: [
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image6.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image7.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image8.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image9.jpg',
      '/images/InstructionGuide/image1.jpg',
      '/images/InstructionGuide/image2.jpg',
      '/images/InstructionGuide/image3.jpg',
      '/images/InstructionGuide/image4.jpg',
      '/images/InstructionGuide/image5.jpg',
    ],
    category: 'cute',
    collection: 'Dễ thương',
    description:
      'Monkey Sundae is a playful and dreamy press-on nail set inspired by sweet desserts and kawaii aesthetics. Featuring soft pink tones, banana and chocolate details, glossy 3D textures, floral accents, and an adorable monkey charm, this set blends candycore vibes with cute luxury nail art for a fun and eye-catching look.',
    material: 'Premium ABS acrylic with gel topcoat',
    inStock: true,
    isNew: true,
    isBestSeller: false,
    availableSizes: SIZES,
    availableShapes: ['Square', 'Rounded Square', 'Oval', 'Almond', 'Coffin'],
    availableLengths: ['Short', 'Medium', 'Long'],
    processingTime: '3-5 business days',
    tags: ['cute', 'kawaii', 'dessert', 'banana', '3d', 'candycore'],
    rating: 4.9,
    reviewCount: 214,
  },
  {
    id: '7',
    name: 'Petal Fantasy',
    slug: 'petal-fantasy',
    price: 45,
    images: [
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image10.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image11.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image12.jpg',
      '/images/InstructionGuide/image1.jpg',
      '/images/InstructionGuide/image2.jpg',
      '/images/InstructionGuide/image3.jpg',
      '/images/InstructionGuide/image4.jpg',
      '/images/InstructionGuide/image5.jpg',
    ],
    category: 'summer',
    collection: 'Mùa hè',
    description:
      'Petal Fantasy is a dreamy and elegant press-on nail set inspired by blooming petals and glossy fantasy textures. Featuring soft pink and cherry-red tones, delicate 3D flowers, flowing swirl details, and glass-like water effects, this set blends romantic floral aesthetics with luxurious artistic nail design for a graceful and eye-catching look.',
    material: 'Premium ABS acrylic with gel topcoat',
    inStock: true,
    isNew: true,
    isBestSeller: true,
    availableSizes: SIZES,
    availableShapes: ['Square', 'Rounded Square', 'Oval', 'Almond', 'Coffin'],
    availableLengths: ['Short', 'Medium', 'Long'],
    processingTime: '3-5 business days',
    tags: ['floral', 'summer', '3d-flowers', 'glossy', 'romantic', 'water-effect', 'luxury'],
    rating: 4.8,
    reviewCount: 173,
  },
  {
    id: '12',
    name: 'Pink Butterfly Cat Eye',
    slug: 'pink-butterfly-cat-eye',
    price: 55,
    images: [
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image13.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image14.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image15.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image16.jpg',
      '/images/InstructionGuide/image1.jpg',
      '/images/InstructionGuide/image2.jpg',
      '/images/InstructionGuide/image3.jpg',
      '/images/InstructionGuide/image4.jpg',
      '/images/InstructionGuide/image5.jpg',
    ],
    category: 'cat-eye',
    collection: 'Cat Eye',
    description:
      'Pink Butterfly Cat Eye is a dreamy and elegant press-on nail set featuring shimmering pink cat-eye effects, butterfly-inspired designs, glossy 3D textures, and luxurious gold details. Blending soft feminine tones with sparkling pearl accents and fantasy aesthetics, this set creates a delicate yet eye-catching look full of elegance and charm.',
    material: 'Premium ABS acrylic with gel topcoat',
    inStock: true,
    isNew: true,
    isBestSeller: true,
    availableSizes: SIZES,
    availableShapes: ['Square', 'Rounded Square', 'Oval', 'Almond', 'Coffin'],
    availableLengths: ['Short', 'Medium', 'Long'],
    processingTime: '3-5 business days',
    tags: ['cat-eye', 'butterfly', 'pink', 'pearl', 'gold', '3d', 'fantasy', 'elegant'],
    rating: 5.0,
    reviewCount: 248,
  },
  {
    id: '18',
    name: 'Heart Blossom Cat Eye',
    slug: 'heart-blossom-cat-eye',
    price: 45,
    images: [
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image17.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image18.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image19.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image20.jpg',
      '/images/InstructionGuide/image1.jpg',
      '/images/InstructionGuide/image2.jpg',
      '/images/InstructionGuide/image3.jpg',
      '/images/InstructionGuide/image4.jpg',
      '/images/InstructionGuide/image5.jpg',
    ],
    category: 'cat-eye',
    collection: 'Cat Eye',
    description:
      'Heart Blossom Cat Eye is a luxurious and feminine press-on nail set featuring green, blue, and purple tones combined with a moonlight cat-eye effect. The design stands out with soft 3D flowers, raised chrome heart details, and delicate gold outlines that create a look both sweet and elegant. The combination of shimmering finishes, butterfly-inspired patterns, and textured elements gives this set a dreamy, elegant appearance that shines beautifully under the light.',
    material: 'Premium ABS acrylic with gel topcoat',
    inStock: true,
    isNew: true,
    isBestSeller: false,
    availableSizes: SIZES,
    availableShapes: ['Square', 'Rounded Square', 'Oval', 'Almond', 'Coffin'],
    availableLengths: ['Short', 'Medium', 'Long'],
    processingTime: '3-5 business days',
    tags: [
      'cat-eye',
      'moonlight',
      'chrome-heart',
      '3d-flowers',
      'butterfly',
      'luxury',
      'shimmer',
      'gold-outline',
    ],
    rating: 4.7,
    reviewCount: 186,
  },
  {
    id: '24',
    name: 'Ivory Gold Bloom',
    slug: 'ivory-gold-bloom',
    price: 48,
    images: [
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image21.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image22.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image23.jpg',
      '/images/InstructionGuide/image1.jpg',
      '/images/InstructionGuide/image2.jpg',
      '/images/InstructionGuide/image3.jpg',
      '/images/InstructionGuide/image4.jpg',
      '/images/InstructionGuide/image5.jpg',
    ],
    category: 'summer',
    collection: 'Mùa hè',
    description:
      'Ivory Gold Bloom is a luxurious and elegant press-on nail set featuring soft ivory nude tones combined with delicate gold metallic details. The design stands out with soft 3D flowers, seashell-inspired patterns, and raised textures that add artistic depth and dimension. Gold charms, pearl accents, and iridescent shell effects give the set a graceful yet eye-catching appearance under the light. This set is perfect for a luxury feminine style with a soft, refined, and high-end aesthetic.',
    material: 'Premium ABS acrylic with gel topcoat',
    inStock: true,
    isNew: true,
    isBestSeller: true,
    availableSizes: SIZES,
    availableShapes: ['Square', 'Rounded Square', 'Oval', 'Almond', 'Coffin'],
    availableLengths: ['Short', 'Medium', 'Long'],
    processingTime: '3-5 business days',
    tags: ['ivory', 'gold', '3d-flowers', 'pearl', 'seashell', 'luxury', 'nude', 'iridescent'],
    rating: 4.9,
    reviewCount: 231,
  },
  {
    id: '31',
    name: 'Pink Seashell Bloom',
    slug: 'pink-seashell-bloom',
    price: 48,
    images: [
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image24.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image25.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image26.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image27.jpg',
      '/images/InstructionGuide/image1.jpg',
      '/images/InstructionGuide/image2.jpg',
      '/images/InstructionGuide/image3.jpg',
      '/images/InstructionGuide/image4.jpg',
      '/images/InstructionGuide/image5.jpg',
    ],
    category: 'summer',
    collection: 'Mùa hè',
    description:
      'Pink Seashell Bloom is a dreamy and feminine press-on nail set inspired by the beauty of seashells and ocean blossoms. Featuring soft pink tones blended with coral accents, the design showcases delicate 3D flowers, seashell-inspired textures, glossy water-drop details, and elegant gold charms. The combination of translucent effects, flowing patterns, and sculpted elements creates a luxurious mermaid-like aesthetic that shines beautifully under the light. Perfect for summer, beach-inspired looks, and anyone who loves romantic ocean fantasy nails.',
    material: 'Premium ABS acrylic with gel topcoat',
    inStock: true,
    isNew: true,
    isBestSeller: true,
    availableSizes: SIZES,
    availableShapes: ['Square', 'Rounded Square', 'Oval', 'Almond', 'Coffin'],
    availableLengths: ['Short', 'Medium', 'Long'],
    processingTime: '3-5 business days',
    tags: [
      'summer',
      'seashell',
      'mermaid',
      'ocean',
      '3d-flowers',
      'pink',
      'coral',
      'water-drop',
      'luxury',
    ],
    rating: 4.8,
    reviewCount: 267,
  },
  {
    id: '326',
    name: 'Timeless Emerald',
    slug: 'timeless-emerald',
    price: 58,
    images: [
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image28.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image29.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image30.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image31.jpg',
      '/images/InstructionGuide/image1.jpg',
      '/images/InstructionGuide/image2.jpg',
      '/images/InstructionGuide/image3.jpg',
      '/images/InstructionGuide/image4.jpg',
      '/images/InstructionGuide/image5.jpg',
    ],
    category: 'summer',
    collection: 'Mùa hè',
    description:
      'Timeless Emerald is a luxurious vintage-inspired press-on nail set featuring elegant sage emerald tones combined with intricate gold details. The design highlights ornate clock motifs, flowing baroque patterns, soft 3D flowers, and sculpted textures that create a regal and timeless aesthetic. With glossy finishes, antique gold accents, and dreamy marble-like swirls, this set captures the feeling of classic elegance blended with fantasy royalty. Perfect for those who love sophisticated statement nails with a vintage luxury vibe.',
    material: 'Premium ABS acrylic with gel topcoat',
    inStock: true,
    isNew: true,
    isBestSeller: true,
    availableSizes: SIZES,
    availableShapes: ['Square', 'Rounded Square', 'Oval', 'Almond', 'Coffin'],
    availableLengths: ['Short', 'Medium', 'Long'],
    processingTime: '3-5 business days',
    tags: [
      'emerald',
      'vintage',
      'baroque',
      'gold',
      'royalty',
      'marble',
      '3d-flowers',
      'luxury',
      'clock-motif',
    ],
    rating: 5.0,
    reviewCount: 312,
  },
  {
    id: '36',
    name: 'Timeless Emerald',
    slug: 'timeless-emerald',
    price: 58,
    images: [
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image28.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image29.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image30.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image31.jpg',
      '/images/InstructionGuide/image1.jpg',
      '/images/InstructionGuide/image2.jpg',
      '/images/InstructionGuide/image3.jpg',
      '/images/InstructionGuide/image4.jpg',
      '/images/InstructionGuide/image5.jpg',
    ],
    category: 'summer',
    collection: 'Mùa hè',
    description:
      'Timeless Emerald is a luxurious vintage-inspired press-on nail set featuring elegant sage emerald tones combined with intricate gold details. The design highlights ornate clock motifs, flowing baroque patterns, soft 3D flowers, and sculpted textures that create a regal and timeless aesthetic. With glossy finishes, antique gold accents, and dreamy marble-like swirls, this set captures the feeling of classic elegance blended with fantasy royalty. Perfect for those who love sophisticated statement nails with a vintage luxury vibe.',
    material: 'Premium ABS acrylic with gel topcoat',
    inStock: true,
    isNew: true,
    isBestSeller: true,
    availableSizes: SIZES,
    availableShapes: ['Square', 'Rounded Square', 'Oval', 'Almond', 'Coffin'],
    availableLengths: ['Short', 'Medium', 'Long'],
    processingTime: '3-5 business days',
    tags: [
      'emerald',
      'vintage',
      'baroque',
      'gold',
      'royalty',
      'marble',
      '3d-flowers',
      'luxury',
      'clock-motif',
    ],
    rating: 5.0,
    reviewCount: 312,
  },
  {
    id: '47',
    name: 'Petal Glow Cat Eye',
    slug: 'petal-glow-cat-eye',
    price: 45,
    images: [
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image35.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image36.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image37.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image38.jpg',
      '/images/InstructionGuide/image1.jpg',
      '/images/InstructionGuide/image2.jpg',
      '/images/InstructionGuide/image3.jpg',
      '/images/InstructionGuide/image4.jpg',
      '/images/InstructionGuide/image5.jpg',
    ],
    category: 'cat-eye',
    collection: 'Cat Eye',
    description:
      'Petal Glow Cat Eye is a luxurious and feminine press-on nail set featuring elegant rose gold cat-eye effects blended with soft nude pink tones. The design is adorned with delicate 3D flower petals, flowing gold chrome lines, pearl accents, and glossy sculpted details that create a refined glowing finish. The shimmering magnetic cat-eye effect adds depth and dimension, while the floral elements bring a romantic and graceful touch. Perfect for elegant occasions, soft glam looks, and anyone who loves classy yet eye-catching nails.',
    material: 'Premium ABS acrylic with gel topcoat',
    inStock: true,
    isNew: true,
    isBestSeller: false,
    availableSizes: SIZES,
    availableShapes: ['Square', 'Rounded Square', 'Oval', 'Almond', 'Coffin'],
    availableLengths: ['Short', 'Medium', 'Long'],
    processingTime: '3-5 business days',
    tags: [
      'cat-eye',
      'rose-gold',
      'floral',
      'pearl',
      'soft-glam',
      'luxury',
      'nude-pink',
      'chrome',
      'elegant',
    ],
    rating: 4.8,
    reviewCount: 205,
  },
  {
    id: '53',
    name: 'Sunset Petal Glow',
    slug: 'sunset-petal-glow',
    price: 50,
    images: [
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image39.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image40.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image41.jpg',
      '/images/InstructionGuide/image1.jpg',
      '/images/InstructionGuide/image2.jpg',
      '/images/InstructionGuide/image3.jpg',
      '/images/InstructionGuide/image4.jpg',
      '/images/InstructionGuide/image5.jpg',
    ],
    category: 'summer',
    collection: 'Mùa hè',
    description:
      'Sunset Petal Glow is a dreamy tropical-inspired press-on nail set featuring warm sunset shades of peach, coral, pink, and soft nude tones. The design showcases delicate 3D flowers, glossy swirl textures, translucent gradients, and luxurious gold accents that create a radiant glowing effect. Inspired by blooming petals under a sunset sky, this set combines romantic floral elements with vibrant summer colors for a playful yet elegant look. Perfect for vacations, summer outfits, beach vibes, and anyone who loves bright feminine nails with artistic details.',
    material: 'Premium ABS acrylic with gel topcoat',
    inStock: true,
    isNew: true,
    isBestSeller: true,
    availableSizes: SIZES,
    availableShapes: ['Square', 'Rounded Square', 'Oval', 'Almond', 'Coffin'],
    availableLengths: ['Short', 'Medium', 'Long'],
    processingTime: '3-5 business days',
    tags: [
      'summer',
      'sunset',
      'coral',
      'peach',
      '3d-flowers',
      'tropical',
      'beach',
      'glow',
      'feminine',
      'luxury',
    ],
    rating: 4.9,
    reviewCount: 276,
  },
  {
    id: '58',
    name: 'Berry Bloom Luxe',
    slug: 'berry-bloom-luxe',
    price: 45,
    images: [
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image42.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image43.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image44.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image45.jpg',
      '/images/InstructionGuide/image1.jpg',
      '/images/InstructionGuide/image2.jpg',
      '/images/InstructionGuide/image3.jpg',
      '/images/InstructionGuide/image4.jpg',
      '/images/InstructionGuide/image5.jpg',
    ],
    category: 'summer',
    collection: 'Mùa hè',
    description:
      'Berry Bloom Luxe is a glamorous press-on nail set featuring rich berry pink tones blended with soft nude shades and luxurious gold accents. The design combines elegant 3D floral details, glossy gradient effects, flowing gold chrome lines, and shimmering embellishments that create a sophisticated feminine look. Inspired by blooming flowers and juicy berry hues, this set delivers a perfect balance of romance, luxury, and modern elegance. Ideal for special occasions, date nights, and anyone who loves bold yet classy statement nails.',
    material: 'Premium ABS acrylic with gel topcoat',
    inStock: true,
    isNew: true,
    isBestSeller: true,
    availableSizes: SIZES,
    availableShapes: ['Square', 'Rounded Square', 'Oval', 'Almond', 'Coffin'],
    availableLengths: ['Short', 'Medium', 'Long'],
    processingTime: '3-5 business days',
    tags: [
      'berry',
      'floral',
      'luxury',
      'gold',
      'gradient',
      'romantic',
      'glamorous',
      'nude',
      'statement',
    ],
    rating: 4.8,
    reviewCount: 243,
  },
  {
    id: '613',
    name: 'Golden Eclipse',
    slug: 'golden-eclipse',
    price: 35,
    images: [
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image46.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image47.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image48.jpg',
      '/images/InstructionGuide/image1.jpg',
      '/images/InstructionGuide/image2.jpg',
      '/images/InstructionGuide/image3.jpg',
      '/images/InstructionGuide/image4.jpg',
      '/images/InstructionGuide/image5.jpg',
    ],
    category: 'cyber-y2k',
    collection: 'Cyber & Y2K',
    description:
      'Golden Eclipse is a luxurious and bold press-on nail set featuring a striking combination of glossy black, white marble swirls, and molten gold chrome details. Inspired by the mysterious beauty of an eclipse, the design blends sculpted metallic textures, flowing abstract patterns, and elegant high-shine finishes for a powerful fashion-forward look. The contrast between deep noir tones and reflective gold elements creates a dramatic, sophisticated aesthetic that feels both modern and royal. Perfect for glam events, statement styling, and lovers of edgy luxury nails.',
    material: 'Premium ABS acrylic with gel topcoat',
    inStock: true,
    isNew: true,
    isBestSeller: false,
    availableSizes: SIZES,
    availableShapes: ['Square', 'Rounded Square', 'Oval', 'Almond', 'Coffin'],
    availableLengths: ['Short', 'Medium', 'Long'],
    processingTime: '3-5 business days',
    tags: [
      'cyber',
      'y2k',
      'black',
      'gold',
      'chrome',
      'marble',
      'luxury',
      'edgy',
      'abstract',
      'glam',
    ],
    rating: 4.7,
    reviewCount: 198,
  },
  {
    id: '63',
    name: 'Golden Eclipse',
    slug: 'golden-eclipse',
    price: 35,
    images: [
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image46.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image47.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image48.jpg',
      '/images/InstructionGuide/image1.jpg',
      '/images/InstructionGuide/image2.jpg',
      '/images/InstructionGuide/image3.jpg',
      '/images/InstructionGuide/image4.jpg',
      '/images/InstructionGuide/image5.jpg',
    ],
    category: 'cyber-y2k',
    collection: 'Cyber & Y2K',
    description:
      'Golden Eclipse is a luxurious and bold press-on nail set featuring a striking combination of glossy black, white marble swirls, and molten gold chrome details. Inspired by the mysterious beauty of an eclipse, the design blends sculpted metallic textures, flowing abstract patterns, and elegant high-shine finishes for a powerful fashion-forward look. The contrast between deep noir tones and reflective gold elements creates a dramatic, sophisticated aesthetic that feels both modern and royal. Perfect for glam events, statement styling, and lovers of edgy luxury nails.',
    material: 'Premium ABS acrylic with gel topcoat',
    inStock: true,
    isNew: true,
    isBestSeller: false,
    availableSizes: SIZES,
    availableShapes: ['Square', 'Rounded Square', 'Oval', 'Almond', 'Coffin'],
    availableLengths: ['Short', 'Medium', 'Long'],
    processingTime: '3-5 business days',
    tags: [
      'cyber',
      'y2k',
      'black',
      'gold',
      'chrome',
      'marble',
      'luxury',
      'edgy',
      'abstract',
      'glam',
    ],
    rating: 4.7,
    reviewCount: 198,
  },
  {
    id: '74',
    name: 'Celestial Glow',
    slug: 'celestial-glow',
    price: 30,
    images: [
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image53.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image54.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image55.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image56.jpg',
      '/images/InstructionGuide/image1.jpg',
      '/images/InstructionGuide/image2.jpg',
      '/images/InstructionGuide/image3.jpg',
      '/images/InstructionGuide/image4.jpg',
      '/images/InstructionGuide/image5.jpg',
    ],
    category: 'cute',
    collection: 'Dễ thương',
    description:
      'Celestial Glow is a dreamy press-on nail set featuring soft pink tones blended with mesmerizing aurora-like holographic effects. Inspired by celestial lights and cosmic fantasy, the design showcases glossy chrome finishes, delicate 3D bows, sparkling star details, and flowing sculpted textures that glow beautifully under different lighting. The combination of iridescent shine and futuristic elegance creates a magical, ethereal aesthetic that feels both sweet and luxurious. Perfect for lovers of soft glam, dreamy galaxy vibes, and statement nails with a radiant celestial glow.',
    material: 'Premium ABS acrylic with gel topcoat',
    inStock: true,
    isNew: true,
    isBestSeller: false,
    availableSizes: SIZES,
    availableShapes: ['Square', 'Rounded Square', 'Oval', 'Almond', 'Coffin'],
    availableLengths: ['Short', 'Medium', 'Long'],
    processingTime: '3-5 business days',
    tags: [
      'celestial',
      'holographic',
      'aurora',
      'galaxy',
      'pink',
      'chrome',
      '3d-bow',
      'star',
      'dreamy',
      'soft-glam',
    ],
    rating: 4.8,
    reviewCount: 184,
  },
  {
    id: '81',
    name: 'Midnight Orchid',
    slug: 'midnight-orchid',
    price: 40,
    images: [
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image57.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image58.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image59.jpg',
      '/images/InstructionGuide/image1.jpg',
      '/images/InstructionGuide/image2.jpg',
      '/images/InstructionGuide/image3.jpg',
      '/images/InstructionGuide/image4.jpg',
      '/images/InstructionGuide/image5.jpg',
    ],
    category: 'summer',
    collection: 'Mùa hè',
    description:
      'Midnight Orchid is a bold and elegant press-on nail set inspired by the mysterious beauty of orchids under the night sky. Featuring deep plum, soft nude, and blush pink tones, the design combines sculpted 3D orchid flowers, glossy jelly effects, delicate dot patterns, and flowing textured details for a luxurious artistic finish. The contrast between dark accents and soft translucent elements creates a dreamy yet dramatic aesthetic that shines beautifully from every angle. Perfect for those who love sophisticated floral nails with a modern mystical vibe.',
    material: 'Premium ABS acrylic with gel topcoat',
    inStock: true,
    isNew: true,
    isBestSeller: false,
    availableSizes: SIZES,
    availableShapes: ['Square', 'Rounded Square', 'Oval', 'Almond', 'Coffin'],
    availableLengths: ['Short', 'Medium', 'Long'],
    processingTime: '3-5 business days',
    tags: [
      'orchid',
      'midnight',
      'plum',
      'floral',
      '3d-flowers',
      'jelly',
      'mystical',
      'elegant',
      'luxury',
    ],
    rating: 4.7,
    reviewCount: 196,
  },
  {
    id: '88',
    name: 'Aurora Bloom',
    slug: 'aurora-bloom',
    price: 45,
    images: [
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image60.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image61.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image62.jpg',
      '/images/InstructionGuide/image1.jpg',
      '/images/InstructionGuide/image2.jpg',
      '/images/InstructionGuide/image3.jpg',
      '/images/InstructionGuide/image4.jpg',
      '/images/InstructionGuide/image5.jpg',
    ],
    category: 'cyber-y2k',
    collection: 'Cyber & Y2K & Chrome Nails',
    description:
      'Aurora Bloom is a mesmerizing press-on nail set inspired by the glowing beauty of the northern lights and blooming fantasy flowers. Featuring radiant pink, lilac, and iridescent chrome tones, the design blends sculpted 3D petals, flowing metallic textures, glossy jelly effects, and luminous holographic reflections for a dreamy futuristic look. The shimmering surface catches the light beautifully from every angle, creating a magical aurora-like glow. Perfect for those who love bold artistic nails with an ethereal and luxurious aesthetic.',
    material: 'Premium ABS acrylic with gel topcoat',
    inStock: true,
    isNew: true,
    isBestSeller: true,
    availableSizes: SIZES,
    availableShapes: ['Square', 'Rounded Square', 'Oval', 'Almond', 'Coffin'],
    availableLengths: ['Short', 'Medium', 'Long'],
    processingTime: '3-5 business days',
    tags: [
      'aurora',
      'chrome',
      'y2k',
      'cyber',
      'holographic',
      'iridescent',
      '3d-petals',
      'jelly',
      'futuristic',
      'luxury',
    ],
    rating: 4.9,
    reviewCount: 274,
  },
  {
    id: '94',
    name: 'Cyber Nebula',
    slug: 'cyber-nebula',
    price: 48,
    images: [
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image63.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image64.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image65.jpg',
      '/images/InstructionGuide/image1.jpg',
      '/images/InstructionGuide/image2.jpg',
      '/images/InstructionGuide/image3.jpg',
      '/images/InstructionGuide/image4.jpg',
      '/images/InstructionGuide/image5.jpg',
    ],
    category: 'cyber-y2k',
    collection: 'Cyber & Y2K & Chrome Nails',
    description:
      'Cyber Nebula is a futuristic press-on nail set inspired by cosmic galaxies and cyberpunk aesthetics. Featuring vibrant pink, violet, and chrome blue tones, the design combines holographic reflections, metallic textures, abstract web patterns, sculpted details, and glowing celestial accents for a bold interstellar look. The mix of glossy chrome finishes and fluid futuristic elements creates a mesmerizing nebula effect that shifts beautifully under the light. Perfect for those who love edgy, space-inspired nails with a high-fashion cyber aesthetic.',
    material: 'Premium ABS acrylic with gel topcoat',
    inStock: true,
    isNew: true,
    isBestSeller: true,
    availableSizes: SIZES,
    availableShapes: ['Square', 'Rounded Square', 'Oval', 'Almond', 'Coffin'],
    availableLengths: ['Short', 'Medium', 'Long'],
    processingTime: '3-5 business days',
    tags: [
      'cyberpunk',
      'nebula',
      'chrome',
      'galaxy',
      'holographic',
      'space',
      'y2k',
      'metallic',
      'futuristic',
      'celestial',
    ],
    rating: 4.9,
    reviewCount: 291,
  },
  {
    id: '101',
    name: 'Phantom Silver',
    slug: 'phantom-silver',
    price: 40,
    images: [
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image66.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image67.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image68.jpg',
      'https://pub-f7a3d0f6a04b429da226cd17dd1d685d.r2.dev/mock-products/image69.jpg',
      '/images/InstructionGuide/image1.jpg',
      '/images/InstructionGuide/image2.jpg',
      '/images/InstructionGuide/image3.jpg',
      '/images/InstructionGuide/image4.jpg',
      '/images/InstructionGuide/image5.jpg',
    ],
    category: 'cat-eye',
    collection: 'Cat Eye',
    description:
      'Phantom Silver is a dark and futuristic press-on nail set inspired by metallic shadows and gothic cyber aesthetics. Featuring striking black, silver chrome, and smoky metallic tones, the design combines sculpted armor-like textures, reflective chrome finishes, celestial details, and fluid abstract elements for a bold high-fashion look. The dramatic contrast between glossy black and luminous silver creates a mysterious phantom-like effect that catches the light beautifully. Perfect for those who love edgy statement nails with a luxurious futuristic vibe.',
    material: 'Premium ABS acrylic with gel topcoat',
    inStock: true,
    isNew: true,
    isBestSeller: false,
    availableSizes: SIZES,
    availableShapes: ['Square', 'Rounded Square', 'Oval', 'Almond', 'Coffin'],
    availableLengths: ['Short', 'Medium', 'Long'],
    processingTime: '3-5 business days',
    tags: [
      'phantom',
      'silver',
      'chrome',
      'gothic',
      'cyber',
      'black',
      'metallic',
      'futuristic',
      'celestial',
      'edgy',
    ],
    rating: 4.8,
    reviewCount: 223,
  },
];

export const getProductById = (id: string) => products.find((p) => p.slug === id);
export const getProductBySlug = (slug: string) => products.find((p) => p.slug === slug);
export const getRelatedProducts = (product: Product, count = 4) =>
  products
    .filter(
      (p) =>
        p.id !== product.id &&
        (p.category === product.category || p.collection === product.collection),
    )
    .slice(0, count);

export const heroImages = {
  main: 'https://images.unsplash.com/photo-1722061608664-f84242d3d2cb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1800',
  secondary:
    'https://images.unsplash.com/photo-1696341980130-4bdff3322802?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1200',
  about1:
    'https://images.unsplash.com/photo-1736628293375-ff94e4874aac?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800',
  about2:
    'https://images.unsplash.com/photo-1759563874675-5bc5c17c9393?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=800',
};
