export type CampaignType =
  | 'hero'
  | 'promotion'
  | 'seasonal'
  | 'collection'
  | 'supply'
  | 'wholesale'
  | 'announcement'
  | 'landing_page';

export type CampaignPlacement =
  | 'homepage_hero'
  | 'homepage_top'
  | 'homepage_middle'
  | 'homepage_bottom'
  | 'collection_page'
  | 'product_page'
  | 'supply_page'
  | 'wholesale_page'
  | 'global';

export type CampaignStatus = 'draft' | 'active' | 'scheduled' | 'expired' | 'archived';

export interface CampaignTranslation {
  id: string;
  locale: string;
  eyebrow: string | null;
  title: string | null;
  subtitle: string | null;
  ctaLabel: string | null;
  secondaryCtaLabel: string | null;
  secondaryCtaUrl: string | null;
  isAutoGenerated: boolean;
}

export interface Campaign {
  id: string;
  name: string;
  type: CampaignType;
  placement: CampaignPlacement;
  status: CampaignStatus;
  desktopImageUrl: string | null;
  mobileImageUrl: string | null;
  ctaUrl: string | null;
  priority: number;
  startsAt: string | null;
  endsAt: string | null;
  overlayOpacity: number;
  translations: CampaignTranslation[];
  createdAt: string;
  updatedAt: string | null;
}

export interface CampaignListResponse {
  items: Campaign[];
  pagination: {
    totalItems: number;
    itemCount: number;
    itemsPerPage: number;
    totalPages: number;
    currentPage: number;
  };
}

export interface CampaignTranslationPayload {
  locale: string;
  eyebrow?: string | null;
  title?: string | null;
  subtitle?: string | null;
  ctaLabel?: string | null;
  secondaryCtaLabel?: string | null;
  secondaryCtaUrl?: string | null;
  isAutoGenerated?: boolean;
}

export interface CreateCampaignPayload {
  name: string;
  type: CampaignType;
  placement: CampaignPlacement;
  status?: CampaignStatus;
  desktopImageUrl?: string | null;
  mobileImageUrl?: string | null;
  ctaUrl?: string | null;
  priority?: number;
  startsAt?: string | null;
  endsAt?: string | null;
  overlayOpacity?: number;
  translations?: CampaignTranslationPayload[];
}

export type UpdateCampaignPayload = Partial<CreateCampaignPayload>;

export const CAMPAIGN_TYPE_LABELS: Record<CampaignType, string> = {
  hero: 'Hero',
  promotion: 'Promotion',
  seasonal: 'Seasonal',
  collection: 'Collection',
  supply: 'Supply',
  wholesale: 'Wholesale',
  announcement: 'Announcement',
  landing_page: 'Landing Page',
};

export const CAMPAIGN_PLACEMENT_LABELS: Record<CampaignPlacement, string> = {
  homepage_hero: 'Homepage Hero',
  homepage_top: 'Homepage Top',
  homepage_middle: 'Homepage Middle',
  homepage_bottom: 'Homepage Bottom',
  collection_page: 'Collection Page',
  product_page: 'Product Page',
  supply_page: 'Supply Page',
  wholesale_page: 'Wholesale Page',
  global: 'Global',
};

export const CAMPAIGN_STATUS_LABELS: Record<CampaignStatus, string> = {
  draft: 'Draft',
  active: 'Active',
  scheduled: 'Scheduled',
  expired: 'Expired',
  archived: 'Archived',
};
