export interface ProductImage {
  id: string;
  url: string;
  isMain: boolean;
}

export interface Product {
  id: string;
  name: string;
  description: string | null;
  basePrice: number | string;
  salePrice: number | string | null;
  currency: string;
  isActive: boolean;
  isNew: boolean;
  isBestSeller: boolean;
  createdAt: string;
  updatedAt: string;
  images: ProductImage[];
}

export interface Pagination {
  totalItems: number;
  itemCount: number;
  itemsPerPage: number;
  totalPages: number;
  currentPage: number;
}

export interface ProductListResponse {
  items: Product[];
  pagination: Pagination;
}

export interface CreateProductPayload {
  name: string;
  description?: string;
  basePrice: number;
  salePrice?: number | null;
  currency?: string;
  isActive?: boolean;
  isNew?: boolean;
  isBestSeller?: boolean;
}

export interface UpdateProductPayload {
  name?: string;
  description?: string | null;
  basePrice?: number;
  salePrice?: number | null;
  currency?: string;
  isActive?: boolean;
  isNew?: boolean;
  isBestSeller?: boolean;
}

// ─── Nail Shapes ─────────────────────────────────────────────────────────────

export interface ApiNailShape {
  id: string;
  name: string;
  sizeTier: 'standard' | 'medium' | 'large' | 'xl';
  lengthMm: number;
  priceAdjustment: number | string;
  adjustmentType: 'fixed' | 'percent';
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface CreateNailShapePayload {
  name: string;
  lengthMm: number;
  sizeTier: 'standard' | 'medium' | 'large' | 'xl';
  priceAdjustment?: number;
  adjustmentType: 'fixed' | 'percent';
  isActive?: boolean;
}

export interface UpdateNailShapePayload {
  name?: string;
  lengthMm?: number;
  sizeTier?: 'standard' | 'medium' | 'large' | 'xl';
  priceAdjustment?: number;
  adjustmentType?: 'fixed' | 'percent';
  isActive?: boolean;
}

// ─── Nail Sizes ──────────────────────────────────────────────────────────────

export interface ApiNailSize {
  id: string;
  label: 'XS' | 'S' | 'M' | 'L' | 'XL' | 'XXL' | 'Custom';
  sizeCode: string;
  measurements: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface CreateNailSizePayload {
  label: 'XS' | 'S' | 'M' | 'L' | 'XL' | 'XXL' | 'Custom';
  sizeCode: string;
  measurements?: string;
}

export interface UpdateNailSizePayload {
  label?: 'XS' | 'S' | 'M' | 'L' | 'XL' | 'XXL' | 'Custom';
  sizeCode?: string;
  measurements?: string | null;
}

// ─── Product Images (API) ─────────────────────────────────────────────────────

export interface ApiProductImage {
  id: string;
  url: string;
  isMain: boolean;
  sortOrder: number;
}

// ─── Product Variants (API) ───────────────────────────────────────────────────

export interface ApiProductVariant {
  id: string;
  sku: string | null;
  stockQty: number;
  computedPrice: number | string;
  isAvailable: boolean;
  createdAt: string;
  updatedAt: string;
  shape: { id: string; name: string; sizeTier: string };
  size: { id: string; label: string; sizeCode: string };
}

// ─── Product Detail (full, with variants + images) ───────────────────────────

export interface ApiProductDetail {
  id: string;
  name: string;
  description: string | null;
  basePrice: number | string;
  salePrice: number | string | null;
  currency: string;
  isActive: boolean;
  isNew: boolean;
  isBestSeller: boolean;
  createdAt: string;
  updatedAt: string;
  images: ApiProductImage[];
  variants: ApiProductVariant[];
}

// ─── Presigned URL ────────────────────────────────────────────────────────────

export interface PresignedUrlResponse {
  presignedUrl: string;
  key: string;
  publicUrl: string;
}

// ─── Image Payloads ───────────────────────────────────────────────────────────

export interface AddImagePayload {
  url: string;
  isMain?: boolean;
}

export interface ReorderImagesPayload {
  orderedIds: string[];
}

// ─── Variant Payloads ─────────────────────────────────────────────────────────

export interface CreateVariantPayload {
  shapeId: string;
  sizeId: string;
  sku?: string;
  stockQty: number;
  computedPrice: number;
  isAvailable?: boolean;
}

export interface UpdateVariantPayload {
  shapeId?: string;
  sizeId?: string;
  sku?: string | null;
  stockQty?: number;
  computedPrice?: number;
  isAvailable?: boolean;
}

// ─── Product Translations ─────────────────────────────────────────────────────

export interface ProductTranslation {
  id: string;
  productId: string;
  locale: string;
  name: string;
  description: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface UpsertProductTranslationPayload {
  name: string;
  description?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
}
