import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  ManyToOne,
  JoinColumn,
  Unique,
  Index,
} from 'typeorm';
import { AbstractEntity } from '../../../common/entities';
import { CollectionEntity } from './collection.entity';

@Entity('collection_translations')
@Unique(['collectionId', 'locale'])
@Index(['locale'])
export class CollectionTranslationEntity extends AbstractEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @ManyToOne(() => CollectionEntity, (c) => c.translations, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'collection_id' })
  collection: CollectionEntity;

  @Column({ name: 'collection_id', type: 'uuid' })
  collectionId: string;

  @Column({ type: 'varchar', length: 10 })
  locale: string;

  @Column({ type: 'varchar', length: 255 })
  name: string;

  @Column({ name: 'short_description', type: 'varchar', length: 500, nullable: true })
  shortDescription: string | null;

  @Column({ type: 'text', nullable: true })
  description: string | null;

  @Column({ name: 'seo_title', type: 'varchar', length: 255, nullable: true })
  seoTitle: string | null;

  @Column({ name: 'seo_description', type: 'text', nullable: true })
  seoDescription: string | null;

  @Column({ name: 'is_auto_generated', type: 'boolean', default: true })
  isAutoGenerated: boolean;
}
