import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  ManyToOne,
  JoinColumn,
  Unique,
  Index,
} from 'typeorm';
import { AbstractEntity } from '../../../common/entities';
import { MarketingCampaignEntity } from './marketing-campaign.entity';

@Entity('marketing_campaign_translations')
@Unique(['campaignId', 'locale'])
@Index(['locale'])
export class MarketingCampaignTranslationEntity extends AbstractEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @ManyToOne(() => MarketingCampaignEntity, (c) => c.translations, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'campaign_id' })
  campaign: MarketingCampaignEntity;

  @Column({ name: 'campaign_id', type: 'uuid' })
  campaignId: string;

  @Column({ type: 'varchar', length: 10 })
  locale: string;

  @Column({ type: 'varchar', length: 255, nullable: true })
  eyebrow: string | null;

  @Column({ type: 'varchar', length: 255, nullable: true })
  title: string | null;

  @Column({ type: 'text', nullable: true })
  subtitle: string | null;

  @Column({ name: 'cta_label', type: 'varchar', length: 100, nullable: true })
  ctaLabel: string | null;

  @Column({ name: 'secondary_cta_label', type: 'varchar', length: 100, nullable: true })
  secondaryCtaLabel: string | null;

  @Column({ name: 'secondary_cta_url', type: 'varchar', length: 2048, nullable: true })
  secondaryCtaUrl: string | null;

  @Column({ name: 'is_auto_generated', type: 'boolean', default: false })
  isAutoGenerated: boolean;
}
