'use client';

import { useState, useEffect, useCallback } from 'react';
import { useTranslation } from 'react-i18next';
import { RefreshCw, Loader2, ChevronDown, ChevronUp, Save } from 'lucide-react';
import type { ProductTranslation, UpsertProductTranslationPayload } from '../../types';
import {
  getProductTranslationsAction,
  upsertProductTranslationAction,
  regenerateProductTranslationsAction,
} from '../../actions';

const LOCALES: { code: string; label: string; flag: string }[] = [
  { code: 'en', label: 'English', flag: '🇬🇧' },
  { code: 'vi', label: 'Vietnamese', flag: '🇻🇳' },
];

interface LocaleCardProps {
  locale: { code: string; label: string; flag: string };
  translation: ProductTranslation | null;
  productId: string;
  onSaved: (tr: ProductTranslation) => void;
}

function LocaleCard({ locale, translation, productId, onSaved }: LocaleCardProps) {
  const { t } = useTranslation('products');
  const [open, setOpen] = useState(false);
  const [name, setName] = useState(translation?.name ?? '');
  const [description, setDescription] = useState(translation?.description ?? '');
  const [seoTitle, setSeoTitle] = useState(translation?.seoTitle ?? '');
  const [seoDescription, setSeoDescription] = useState(translation?.seoDescription ?? '');
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    setName(translation?.name ?? '');
    setDescription(translation?.description ?? '');
    setSeoTitle(translation?.seoTitle ?? '');
    setSeoDescription(translation?.seoDescription ?? '');
  }, [translation]);

  const handleSave = async () => {
    if (!name.trim()) return;
    setSaving(true);
    setError('');
    const payload: UpsertProductTranslationPayload = {
      name: name.trim(),
      description: description.trim() || null,
      seoTitle: seoTitle.trim() || null,
      seoDescription: seoDescription.trim() || null,
    };
    const result = await upsertProductTranslationAction(productId, locale.code, payload);
    setSaving(false);
    if (result.success) {
      onSaved(result.data);
      setOpen(false);
    } else {
      setError((result as { error: string }).error);
    }
  };

  const hasTranslation = !!translation;
  const isAutoGenerated = translation?.isAutoGenerated ?? false;

  return (
    <div className="border border-[#E5E7EB] rounded-lg overflow-hidden">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        className="w-full flex items-center justify-between px-4 py-3 bg-[#F9FAFB] hover:bg-[#F3F4F6] transition-colors text-left"
      >
        <div className="flex items-center gap-2.5">
          <span className="text-base">{locale.flag}</span>
          <span className="text-sm font-medium text-[#374151]">{locale.label}</span>
          {hasTranslation ? (
            <span
              className={`text-[10px] px-1.5 py-0.5 rounded font-medium ${
                isAutoGenerated
                  ? 'bg-amber-100 text-amber-700'
                  : 'bg-emerald-100 text-emerald-700'
              }`}
            >
              {isAutoGenerated ? t('translations.statusAuto') : t('translations.statusManual')}
            </span>
          ) : (
            <span className="text-[10px] px-1.5 py-0.5 rounded font-medium bg-[#F3F4F6] text-[#9CA3AF]">
              {t('translations.statusMissing')}
            </span>
          )}
        </div>
        {open ? (
          <ChevronUp className="w-4 h-4 text-[#9CA3AF]" />
        ) : (
          <ChevronDown className="w-4 h-4 text-[#9CA3AF]" />
        )}
      </button>

      {open && (
        <div className="p-4 space-y-3">
          {error && (
            <p className="text-xs text-red-500 bg-red-50 px-3 py-2 rounded-lg border border-red-100">
              {error}
            </p>
          )}
          <div>
            <label className="block text-xs font-semibold mb-1 text-[#374151]">{t('translations.name')}</label>
            <input
              value={name}
              onChange={(e) => setName(e.target.value)}
              className="w-full px-3 py-2 border border-[#E5E7EB] rounded-lg text-sm outline-none focus:border-[#111827] transition-colors"
              placeholder={t('translations.namePlaceholder', { locale: locale.label })}
            />
          </div>
          <div>
            <label className="block text-xs font-semibold mb-1 text-[#374151]">
              {t('translations.description')}
            </label>
            <textarea
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              rows={3}
              className="w-full px-3 py-2 border border-[#E5E7EB] rounded-lg text-sm outline-none focus:border-[#111827] transition-colors resize-none"
              placeholder={t('translations.descriptionPlaceholder', { locale: locale.label })}
            />
          </div>
          <div>
            <label className="block text-xs font-semibold mb-1 text-[#374151]">
              {t('translations.seoTitle')}
            </label>
            <input
              value={seoTitle}
              onChange={(e) => setSeoTitle(e.target.value)}
              className="w-full px-3 py-2 border border-[#E5E7EB] rounded-lg text-sm outline-none focus:border-[#111827] transition-colors"
            />
          </div>
          <div>
            <label className="block text-xs font-semibold mb-1 text-[#374151]">
              {t('translations.seoDescription')}
            </label>
            <textarea
              value={seoDescription}
              onChange={(e) => setSeoDescription(e.target.value)}
              rows={2}
              className="w-full px-3 py-2 border border-[#E5E7EB] rounded-lg text-sm outline-none focus:border-[#111827] transition-colors resize-none"
            />
          </div>
          <button
            type="button"
            onClick={handleSave}
            disabled={!name.trim() || saving}
            className="flex items-center gap-2 px-4 py-2 rounded-lg bg-[#111827] text-white text-xs font-medium hover:bg-[#374151] transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {saving ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Save className="w-3.5 h-3.5" />}
            {saving ? t('translations.saving') : t('translations.save')}
          </button>
        </div>
      )}
    </div>
  );
}

interface Props {
  productId: string;
}

export default function ProductTranslationsTab({ productId }: Props) {
  const { t } = useTranslation('products');
  const [translations, setTranslations] = useState<ProductTranslation[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [regenerating, setRegenerating] = useState(false);
  const [regenMsg, setRegenMsg] = useState('');

  const load = useCallback(async () => {
    setLoading(true);
    setError('');
    const result = await getProductTranslationsAction(productId);
    if (result.success) {
      setTranslations(result.data);
    } else {
      setError((result as { error: string }).error);
    }
    setLoading(false);
  }, [productId]);

  useEffect(() => {
    load();
  }, [load]);

  const handleRegenerate = async () => {
    setRegenerating(true);
    setRegenMsg('');
    const result = await regenerateProductTranslationsAction(productId);
    setRegenerating(false);
    if (result.success) {
      setRegenMsg(t('translations.queued'));
      setTimeout(() => load(), 2000);
    } else {
      setRegenMsg((result as { error: string }).error);
    }
  };

  const handleSaved = (tr: ProductTranslation) => {
    setTranslations((prev) => {
      const idx = prev.findIndex((t) => t.locale === tr.locale);
      if (idx >= 0) {
        const copy = [...prev];
        copy[idx] = tr;
        return copy;
      }
      return [...prev, tr];
    });
  };

  const trByLocale = (code: string) => translations.find((t) => t.locale === code) ?? null;

  if (loading) {
    return (
      <div className="flex-1 flex items-center justify-center">
        <Loader2 className="w-5 h-5 text-[#9CA3AF] animate-spin" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex-1 flex items-center justify-center px-6">
        <p className="text-sm text-red-500 text-center">{error}</p>
      </div>
    );
  }

  return (
    <div className="flex-1 overflow-y-auto p-4 sm:p-6 space-y-4">
      <div className="flex items-center justify-between">
        <p className="text-xs text-[#6B7280]">
          {t('translations.progress', { done: translations.length, total: LOCALES.length })}
        </p>
        <button
          type="button"
          onClick={handleRegenerate}
          disabled={regenerating}
          className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-[#374151] border border-[#E5E7EB] rounded-lg hover:bg-[#F3F4F6] transition-colors disabled:opacity-50"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${regenerating ? 'animate-spin' : ''}`} />
          {regenerating ? t('translations.generating') : t('translations.autoAll')}
        </button>
      </div>

      {regenMsg && (
        <p className="text-xs text-[#6B7280] bg-[#F9FAFB] px-3 py-2 rounded-lg border border-[#E5E7EB]">
          {regenMsg}
        </p>
      )}

      <div className="space-y-2">
        {LOCALES.map((locale) => (
          <LocaleCard
            key={locale.code}
            locale={locale}
            translation={trByLocale(locale.code)}
            productId={productId}
            onSaved={handleSaved}
          />
        ))}
      </div>
    </div>
  );
}
