import { Entity, PrimaryGeneratedColumn, Column, Unique, Index } from 'typeorm';
import { AbstractEntity } from '../../../common/entities';

export type I18nEntityType = 'product' | 'product_variant' | 'collection';

@Entity('i18n_translations')
@Unique(['entityType', 'entityId', 'locale'])
@Index(['locale'])
@Index(['entityType', 'entityId'])
export class I18nTranslationEntity extends AbstractEntity {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ name: 'entity_type', type: 'varchar', length: 50 })
  entityType: string;

  @Column({ name: 'entity_id', type: 'varchar', length: 36 })
  entityId: string;

  @Column({ type: 'varchar', length: 10 })
  locale: string;

  /** Translated name / color name — required for all current entity types. */
  @Column({ type: 'varchar', length: 255, nullable: true })
  name: string | null;

  @Column({ type: 'text', nullable: true })
  description: string | null;

  @Column({ name: 'short_description', type: 'varchar', length: 500, nullable: true })
  shortDescription: string | null;

  @Column({ name: 'seo_title', type: 'varchar', length: 255, nullable: true })
  seoTitle: string | null;

  @Column({ name: 'seo_description', type: 'text', nullable: true })
  seoDescription: string | null;

  @Column({ name: 'is_auto_generated', type: 'boolean', default: true })
  isAutoGenerated: boolean;
}
