export interface ShippingZone {
  name: string;
  fee: number;
  currency: string;
  isoCodes: string[];
  aliases: string[];
}

export const SHIPPING_ZONES: ShippingZone[] = [
  {
    name: 'Zone A',
    fee: 10,
    currency: 'USD',
    isoCodes: ['my', 'bn', 'id', 'ph', 'th', 'vu'],
    aliases: ['malaysia', 'brunei', 'indonesia', 'philippines', 'thailand', 'vanuatu'],
  },
  {
    name: 'Zone B',
    fee: 15,
    currency: 'USD',
    isoCodes: [
      'tw',
      'in',
      'cn',
      'mn',
      'bd',
      'la',
      'kh',
      'mm',
      'ki',
      'tv',
      'be',
      'it',
      'us',
      'au',
      'gb',
      'de',
      'ca',
      'jp',
      'nz',
      'sg',
      'hk',
      'ae',
      'sa',
      // EU members not listed in Zone C
      'at',
      'bg',
      'hr',
      'cy',
      'cz',
      'fi',
      'fr',
      'gr',
      'lv',
      'lt',
      'lu',
      'mt',
      'nl',
      'pt',
      'ro',
      'sk',
      'si',
      'es',
      'se',
    ],
    aliases: [
      'taiwan',
      'india',
      'china',
      'mongolia',
      'bangladesh',
      'laos',
      'cambodia',
      'myanmar',
      'kiribati',
      'tuvalu',
      'belgium',
      'italy',
      'united states',
      'usa',
      'australia',
      'united kingdom',
      'uk',
      'great britain',
      'germany',
      'canada',
      'japan',
      'new zealand',
      'singapore',
      'hong kong',
      'uae',
      'united arab emirates',
      'saudi arabia',
      'austria',
      'bulgaria',
      'croatia',
      'cyprus',
      'czech republic',
      'czechia',
      'finland',
      'france',
      'greece',
      'latvia',
      'lithuania',
      'luxembourg',
      'malta',
      'netherlands',
      'portugal',
      'romania',
      'slovakia',
      'slovenia',
      'spain',
      'sweden',
    ],
  },
  {
    name: 'Zone C',
    fee: 20,
    currency: 'USD',
    isoCodes: [
      'ch',
      'hu',
      'dk',
      'pl',
      'ee',
      'ie',
      'no',
      'gi',
      'je',
      'cl',
      'mx',
      'br',
      'eg',
      'ec',
      'jo',
      'py',
    ],
    aliases: [
      'switzerland',
      'hungary',
      'denmark',
      'poland',
      'estonia',
      'ireland',
      'norway',
      'gibraltar',
      'jersey',
      'chile',
      'mexico',
      'brazil',
      'egypt',
      'ecuador',
      'jordan',
      'paraguay',
    ],
  },
  {
    name: 'Zone D',
    fee: 25,
    currency: 'USD',
    isoCodes: ['ar', 'co', 'kw'],
    aliases: ['argentina', 'colombia', 'kuwait'],
  },
];

/** Find zone by ISO alpha-2 code (e.g. "US") or country name (e.g. "United States"). */
export function getShippingZone(country: string): ShippingZone | null {
  if (!country?.trim()) return null;
  const normalized = country.toLowerCase().trim();
  return (
    SHIPPING_ZONES.find((z) => z.isoCodes.includes(normalized) || z.aliases.includes(normalized)) ??
    null
  );
}
