import type { Step } from './types';

// Vietnam – Free
// Zone A – $10: Malaysia, Brunei, Indonesia, Philippines, Thailand, Vanuatu
// Zone B – $15: Taiwan, India, China, Mongolia, Bangladesh, Laos, Cambodia, Myanmar,
//               Kiribati, Tuvalu, Belgium, Italy, United States, Australia, United Kingdom,
//               Germany, Canada, Japan, New Zealand, Singapore, Hong Kong, United Arab Emirates,
//               Saudi Arabia, Austria, Bulgaria, Croatia, Cyprus, Czech Republic, Finland,
//               France, Greece, Latvia, Lithuania, Luxembourg, Malta, Netherlands, Portugal,
//               Romania, Slovakia, Slovenia, Spain, Sweden
// Zone C – $20: Switzerland, Hungary, Denmark, Poland, Estonia, Ireland, Norway, Gibraltar,
//               Jersey, Chile, Mexico, Brazil, Egypt, Ecuador, Jordan, Paraguay
// Zone D – $25: Argentina, Colombia, Kuwait
export const COUNTRIES = [
  'Argentina',
  'Australia',
  'Austria',
  'Bangladesh',
  'Belgium',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Cambodia',
  'Canada',
  'Chile',
  'China',
  'Colombia',
  'Croatia',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Ecuador',
  'Egypt',
  'Estonia',
  'Finland',
  'France',
  'Germany',
  'Gibraltar',
  'Greece',
  'Hong Kong',
  'Hungary',
  'India',
  'Indonesia',
  'Ireland',
  'Italy',
  'Japan',
  'Jersey',
  'Jordan',
  'Kiribati',
  'Kuwait',
  'Laos',
  'Latvia',
  'Lithuania',
  'Luxembourg',
  'Malaysia',
  'Malta',
  'Mexico',
  'Mongolia',
  'Myanmar',
  'Netherlands',
  'New Zealand',
  'Norway',
  'Paraguay',
  'Philippines',
  'Poland',
  'Portugal',
  'Romania',
  'Saudi Arabia',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Spain',
  'Sweden',
  'Switzerland',
  'Taiwan',
  'Thailand',
  'Tuvalu',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Vanuatu',
  'Vietnam',
  'Other',
] as const;

export const CHECKOUT_STEPS: { key: Step; labelKey: string }[] = [
  { key: 'contact', labelKey: 'steps.contact' },
  { key: 'shipping', labelKey: 'steps.shipping' },
  { key: 'payment', labelKey: 'steps.payment' },
];

export const PAYMENT_METHODS = ['airwallex'] as const;

export const DEFAULT_CONTACT = { email: '', phone: '', fullName: '' };
export const DEFAULT_SHIPPING = {
  firstName: '',
  lastName: '',
  address: '',
  apartment: '',
  city: '',
  postalCode: '',
  country: 'Vietnam',
};
