'use client';

import { useState, useEffect, useCallback } from 'react';
import { RefreshCw, Loader2, ChevronDown, ChevronUp, Save, Languages } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import type { CollectionTranslation, UpsertCollectionTranslationPayload } from '../types';
import {
  getCollectionTranslationsAction,
  upsertCollectionTranslationAction,
  regenerateCollectionTranslationsAction,
} from '../actions';

const LOCALES: { code: string; label: string; flag: string }[] = [
  { code: 'en', label: 'English', flag: '🇬🇧' },
  { code: 'vi', label: 'Vietnamese', flag: '🇻🇳' },
];

interface LocaleCardProps {
  locale: { code: string; label: string; flag: string };
  translation: CollectionTranslation | null;
  collectionId: string;
  onSaved: (tr: CollectionTranslation) => void;
}

function LocaleCard({ locale, translation, collectionId, onSaved }: LocaleCardProps) {
  const { t } = useTranslation('collections');
  const [open, setOpen] = useState(false);
  const [name, setName] = useState(translation?.name ?? '');
  const [shortDescription, setShortDescription] = useState(translation?.shortDescription ?? '');
  const [description, setDescription] = useState(translation?.description ?? '');
  const [seoTitle, setSeoTitle] = useState(translation?.seoTitle ?? '');
  const [seoDescription, setSeoDescription] = useState(translation?.seoDescription ?? '');
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    setName(translation?.name ?? '');
    setShortDescription(translation?.shortDescription ?? '');
    setDescription(translation?.description ?? '');
    setSeoTitle(translation?.seoTitle ?? '');
    setSeoDescription(translation?.seoDescription ?? '');
  }, [translation]);

  const handleSave = async () => {
    if (!name.trim()) return;
    setSaving(true);
    setError('');
    const payload: UpsertCollectionTranslationPayload = {
      name: name.trim(),
      shortDescription: shortDescription.trim() || null,
      description: description.trim() || null,
      seoTitle: seoTitle.trim() || null,
      seoDescription: seoDescription.trim() || null,
    };
    const result = await upsertCollectionTranslationAction(collectionId, locale.code, payload);
    setSaving(false);
    if (result.success) {
      onSaved(result.data);
      setOpen(false);
    } else {
      setError((result as { error: string }).error);
    }
  };

  const hasTranslation = !!translation;
  const isAutoGenerated = translation?.isAutoGenerated ?? false;

  return (
    <div className="border border-[#E5E7EB] rounded-lg overflow-hidden">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        className="w-full flex items-center justify-between px-4 py-3 bg-[#F9FAFB] hover:bg-[#F3F4F6] transition-colors text-left"
      >
        <div className="flex items-center gap-2.5">
          <span className="text-base">{locale.flag}</span>
          <span className="text-sm font-medium text-[#374151]">{locale.label}</span>
          {hasTranslation ? (
            <span
              className={`text-[10px] px-1.5 py-0.5 rounded font-medium ${
                isAutoGenerated
                  ? 'bg-amber-100 text-amber-700'
                  : 'bg-emerald-100 text-emerald-700'
              }`}
            >
              {isAutoGenerated ? t('translations.statusAuto') : t('translations.statusManual')}
            </span>
          ) : (
            <span className="text-[10px] px-1.5 py-0.5 rounded font-medium bg-[#F3F4F6] text-[#9CA3AF]">
              {t('translations.statusMissing')}
            </span>
          )}
        </div>
        {open ? (
          <ChevronUp className="w-4 h-4 text-[#9CA3AF]" />
        ) : (
          <ChevronDown className="w-4 h-4 text-[#9CA3AF]" />
        )}
      </button>

      {open && (
        <div className="p-4 space-y-3">
          {error && (
            <p className="text-xs text-red-500 bg-red-50 px-3 py-2 rounded-lg border border-red-100">
              {error}
            </p>
          )}
          <div>
            <label className="block text-xs font-semibold mb-1 text-[#374151]">{t('translations.name')} *</label>
            <input
              value={name}
              onChange={(e) => setName(e.target.value)}
              className="w-full px-3 py-2 border border-[#E5E7EB] rounded-lg text-sm outline-none focus:border-[#111827] transition-colors"
              placeholder={t('translations.namePlaceholder', { locale: locale.label })}
            />
          </div>
          <div>
            <label className="block text-xs font-semibold mb-1 text-[#374151]">
              {t('translations.shortDescription')} <span className="font-normal text-[#9CA3AF]">{t('translations.optional')}</span>
            </label>
            <input
              value={shortDescription}
              onChange={(e) => setShortDescription(e.target.value)}
              className="w-full px-3 py-2 border border-[#E5E7EB] rounded-lg text-sm outline-none focus:border-[#111827] transition-colors"
            />
          </div>
          <div>
            <label className="block text-xs font-semibold mb-1 text-[#374151]">
              {t('translations.description')} <span className="font-normal text-[#9CA3AF]">{t('translations.optional')}</span>
            </label>
            <textarea
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              rows={3}
              className="w-full px-3 py-2 border border-[#E5E7EB] rounded-lg text-sm outline-none focus:border-[#111827] transition-colors resize-none"
            />
          </div>
          <div>
            <label className="block text-xs font-semibold mb-1 text-[#374151]">
              {t('translations.seoTitle')} <span className="font-normal text-[#9CA3AF]">{t('translations.optional')}</span>
            </label>
            <input
              value={seoTitle}
              onChange={(e) => setSeoTitle(e.target.value)}
              className="w-full px-3 py-2 border border-[#E5E7EB] rounded-lg text-sm outline-none focus:border-[#111827] transition-colors"
            />
          </div>
          <div>
            <label className="block text-xs font-semibold mb-1 text-[#374151]">
              {t('translations.seoDescription')} <span className="font-normal text-[#9CA3AF]">{t('translations.optional')}</span>
            </label>
            <textarea
              value={seoDescription}
              onChange={(e) => setSeoDescription(e.target.value)}
              rows={2}
              className="w-full px-3 py-2 border border-[#E5E7EB] rounded-lg text-sm outline-none focus:border-[#111827] transition-colors resize-none"
            />
          </div>
          <button
            type="button"
            onClick={handleSave}
            disabled={!name.trim() || saving}
            className="flex items-center gap-2 px-4 py-2 rounded-lg bg-[#111827] text-white text-xs font-medium hover:bg-[#374151] transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {saving ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Save className="w-3.5 h-3.5" />}
            {saving ? t('translations.saving') : t('translations.save')}
          </button>
        </div>
      )}
    </div>
  );
}

interface Props {
  collectionId: string;
}

export function CollectionTranslationsSection({ collectionId }: Props) {
  const { t } = useTranslation('collections');
  const [expanded, setExpanded] = useState(false);
  const [translations, setTranslations] = useState<CollectionTranslation[]>([]);
  const [loading, setLoading] = useState(false);
  const [loaded, setLoaded] = useState(false);
  const [error, setError] = useState('');
  const [regenerating, setRegenerating] = useState(false);
  const [regenMsg, setRegenMsg] = useState('');

  const load = useCallback(async () => {
    setLoading(true);
    setError('');
    const result = await getCollectionTranslationsAction(collectionId);
    if (result.success) {
      setTranslations(result.data);
      setLoaded(true);
    } else {
      setError((result as { error: string }).error);
    }
    setLoading(false);
  }, [collectionId]);

  const handleToggle = () => {
    if (!expanded && !loaded) load();
    setExpanded((v) => !v);
  };

  const handleRegenerate = async () => {
    setRegenerating(true);
    setRegenMsg('');
    const result = await regenerateCollectionTranslationsAction(collectionId);
    setRegenerating(false);
    if (result.success) {
      setRegenMsg(t('translations.queued'));
      setTimeout(() => load(), 2000);
    } else {
      setRegenMsg((result as { error: string }).error);
    }
  };

  const handleSaved = (tr: CollectionTranslation) => {
    setTranslations((prev) => {
      const idx = prev.findIndex((t) => t.locale === tr.locale);
      if (idx >= 0) {
        const copy = [...prev];
        copy[idx] = tr;
        return copy;
      }
      return [...prev, tr];
    });
  };

  const trByLocale = (code: string) => translations.find((t) => t.locale === code) ?? null;

  return (
    <div className="border-t border-[#E5E7EB] pt-5">
      <button
        type="button"
        onClick={handleToggle}
        className="w-full flex items-center justify-between mb-3"
      >
        <div className="flex items-center gap-2">
          <Languages className="w-4 h-4 text-[#6B7280]" />
          <p className="text-xs font-semibold text-[#6B7280] uppercase tracking-wide">{t('translations.title')}</p>
          {loaded && (
            <span className="text-[10px] text-[#9CA3AF]">
              {translations.length}/{LOCALES.length}
            </span>
          )}
        </div>
        {expanded ? (
          <ChevronUp className="w-4 h-4 text-[#9CA3AF]" />
        ) : (
          <ChevronDown className="w-4 h-4 text-[#9CA3AF]" />
        )}
      </button>

      {expanded && (
        <div className="space-y-3">
          {loading && (
            <div className="flex justify-center py-4">
              <Loader2 className="w-5 h-5 text-[#9CA3AF] animate-spin" />
            </div>
          )}

          {error && (
            <p className="text-xs text-red-500 bg-red-50 px-3 py-2 rounded-lg border border-red-100">
              {error}
            </p>
          )}

          {loaded && !loading && (
            <>
              <div className="flex items-center justify-between">
                <span className="text-xs text-[#9CA3AF]">
                  {t('translations.manage')}
                </span>
                <button
                  type="button"
                  onClick={handleRegenerate}
                  disabled={regenerating}
                  className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-[#374151] border border-[#E5E7EB] rounded-lg hover:bg-[#F3F4F6] transition-colors disabled:opacity-50"
                >
                  <RefreshCw className={`w-3.5 h-3.5 ${regenerating ? 'animate-spin' : ''}`} />
                  {regenerating ? t('translations.generating') : t('translations.autoAll')}
                </button>
              </div>

              {regenMsg && (
                <p className="text-xs text-[#6B7280] bg-[#F9FAFB] px-3 py-2 rounded-lg border border-[#E5E7EB]">
                  {regenMsg}
                </p>
              )}

              <div className="space-y-2">
                {LOCALES.map((locale) => (
                  <LocaleCard
                    key={locale.code}
                    locale={locale}
                    translation={trByLocale(locale.code)}
                    collectionId={collectionId}
                    onSaved={handleSaved}
                  />
                ))}
              </div>
            </>
          )}
        </div>
      )}
    </div>
  );
}
