import { Inject, Injectable, Logger, Optional } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';

import { ProductTranslationEntity } from '@/db/entities/products/product-translation.entity';
import { CollectionTranslationEntity } from '@/db/entities/products/collection-translation.entity';

import { LanguageDetectionService } from './language-detection.service';
import { SUPPORTED_LOCALES, FALLBACK_LOCALE, TRANSLATION_PROVIDER_TOKEN } from './translation.constants';
import type { SupportedLocale } from './translation.constants';
import type { ITranslationProvider } from './translation.provider.interface';

export interface TranslatableProductFields {
  id: string;
  name: string;
  description?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
}

export interface TranslatableCollectionFields {
  id: string;
  name: string;
  shortDescription?: string | null;
  description?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
}

@Injectable()
export class TranslationService {
  private readonly logger = new Logger(TranslationService.name);

  constructor(
    @InjectRepository(ProductTranslationEntity)
    private readonly productTranslationRepo: Repository<ProductTranslationEntity>,
    @InjectRepository(CollectionTranslationEntity)
    private readonly collectionTranslationRepo: Repository<CollectionTranslationEntity>,
    private readonly langDetector: LanguageDetectionService,
    @Optional()
    @Inject(TRANSLATION_PROVIDER_TOKEN)
    private readonly provider: ITranslationProvider | null,
  ) {}

  // ─── Product translations ─────────────────────────────────────────────────────

  async generateForProduct(product: TranslatableProductFields): Promise<void> {
    const sourceLang = this.langDetector.detect(product.name);
    const missingLocales = SUPPORTED_LOCALES.filter((l) => l !== sourceLang);

    // Upsert source locale first
    await this.upsertProductTranslation(product, sourceLang, {
      name: product.name,
      description: product.description ?? null,
      seoTitle: product.seoTitle ?? null,
      seoDescription: product.seoDescription ?? null,
      isAutoGenerated: false,
    });

    // Generate missing locales
    for (const targetLang of missingLocales) {
      try {
        const translated = await this.translateProductFields(product, sourceLang, targetLang);
        await this.upsertProductTranslation(product, targetLang, {
          ...translated,
          isAutoGenerated: true,
        });
      } catch (err) {
        this.logger.error(
          `Failed to generate ${targetLang} translation for product ${product.id}: ${(err as Error).message}`,
        );
      }
    }
  }

  async upsertProductTranslation(
    product: TranslatableProductFields,
    locale: SupportedLocale,
    fields: {
      name: string;
      description: string | null;
      seoTitle: string | null;
      seoDescription: string | null;
      isAutoGenerated: boolean;
    },
  ): Promise<ProductTranslationEntity> {
    const existing = await this.productTranslationRepo.findOne({
      where: { productId: product.id, locale },
    });

    if (existing) {
      existing.name = fields.name;
      existing.description = fields.description;
      existing.seoTitle = fields.seoTitle;
      existing.seoDescription = fields.seoDescription;
      existing.isAutoGenerated = fields.isAutoGenerated;
      return this.productTranslationRepo.save(existing);
    }

    const translation = this.productTranslationRepo.create({
      productId: product.id,
      locale,
      name: fields.name,
      description: fields.description,
      seoTitle: fields.seoTitle,
      seoDescription: fields.seoDescription,
      isAutoGenerated: fields.isAutoGenerated,
    });

    return this.productTranslationRepo.save(translation);
  }

  async getProductTranslations(productId: string): Promise<ProductTranslationEntity[]> {
    return this.productTranslationRepo.find({
      where: { productId },
      order: { locale: 'ASC' },
    });
  }

  async getProductTranslation(
    productId: string,
    locale: SupportedLocale,
  ): Promise<ProductTranslationEntity | null> {
    return (
      (await this.productTranslationRepo.findOne({ where: { productId, locale } })) ??
      (locale !== FALLBACK_LOCALE
        ? this.productTranslationRepo.findOne({ where: { productId, locale: FALLBACK_LOCALE } })
        : null)
    );
  }

  // ─── Collection translations ─────────────────────────────────────────────────

  async generateForCollection(collection: TranslatableCollectionFields): Promise<void> {
    const sourceLang = this.langDetector.detect(collection.name);
    const missingLocales = SUPPORTED_LOCALES.filter((l) => l !== sourceLang);

    await this.upsertCollectionTranslation(collection, sourceLang, {
      name: collection.name,
      shortDescription: collection.shortDescription ?? null,
      description: collection.description ?? null,
      seoTitle: collection.seoTitle ?? null,
      seoDescription: collection.seoDescription ?? null,
      isAutoGenerated: false,
    });

    for (const targetLang of missingLocales) {
      try {
        const translated = await this.translateCollectionFields(
          collection,
          sourceLang,
          targetLang,
        );
        await this.upsertCollectionTranslation(collection, targetLang, {
          ...translated,
          isAutoGenerated: true,
        });
      } catch (err) {
        this.logger.error(
          `Failed to generate ${targetLang} translation for collection ${collection.id}: ${(err as Error).message}`,
        );
      }
    }
  }

  async upsertCollectionTranslation(
    collection: TranslatableCollectionFields,
    locale: SupportedLocale,
    fields: {
      name: string;
      shortDescription: string | null;
      description: string | null;
      seoTitle: string | null;
      seoDescription: string | null;
      isAutoGenerated: boolean;
    },
  ): Promise<CollectionTranslationEntity> {
    const existing = await this.collectionTranslationRepo.findOne({
      where: { collectionId: collection.id, locale },
    });

    if (existing) {
      existing.name = fields.name;
      existing.shortDescription = fields.shortDescription;
      existing.description = fields.description;
      existing.seoTitle = fields.seoTitle;
      existing.seoDescription = fields.seoDescription;
      existing.isAutoGenerated = fields.isAutoGenerated;
      return this.collectionTranslationRepo.save(existing);
    }

    const translation = this.collectionTranslationRepo.create({
      collectionId: collection.id,
      locale,
      name: fields.name,
      shortDescription: fields.shortDescription,
      description: fields.description,
      seoTitle: fields.seoTitle,
      seoDescription: fields.seoDescription,
      isAutoGenerated: fields.isAutoGenerated,
    });

    return this.collectionTranslationRepo.save(translation);
  }

  async getCollectionTranslations(collectionId: string): Promise<CollectionTranslationEntity[]> {
    return this.collectionTranslationRepo.find({
      where: { collectionId },
      order: { locale: 'ASC' },
    });
  }

  async getCollectionTranslation(
    collectionId: string,
    locale: SupportedLocale,
  ): Promise<CollectionTranslationEntity | null> {
    return (
      (await this.collectionTranslationRepo.findOne({ where: { collectionId, locale } })) ??
      (locale !== FALLBACK_LOCALE
        ? this.collectionTranslationRepo.findOne({
            where: { collectionId, locale: FALLBACK_LOCALE },
          })
        : null)
    );
  }

  // ─── Utility ─────────────────────────────────────────────────────────────────

  /**
   * Returns the English version of a name, used for slug generation.
   * If the name is already English, returns it unchanged.
   * If a translation provider is available it translates; otherwise falls back to the original.
   */
  async resolveEnglishName(name: string): Promise<string> {
    const sourceLang = this.langDetector.detect(name);
    if (sourceLang === 'en' || !this.provider?.isAvailable()) return name;
    try {
      const { translatedText } = await this.provider.translate({
        text: name,
        sourceLang,
        targetLang: 'en',
        context: 'product or collection name for URL slug generation — short, keep proper nouns',
      });
      return translatedText || name;
    } catch {
      return name;
    }
  }

  // ─── Private translation helpers ─────────────────────────────────────────────

  private async translateText(
    text: string | null | undefined,
    sourceLang: SupportedLocale,
    targetLang: SupportedLocale,
    context: string,
  ): Promise<string | null> {
    if (!text?.trim()) return null;
    if (!this.provider?.isAvailable()) return text;

    const { translatedText } = await this.provider.translate({
      text,
      sourceLang,
      targetLang,
      context,
    });

    return translatedText;
  }

  private async translateProductFields(
    product: TranslatableProductFields,
    sourceLang: SupportedLocale,
    targetLang: SupportedLocale,
  ) {
    const [name, description, seoTitle, seoDescription] = await Promise.all([
      this.translateText(product.name, sourceLang, targetLang, 'nail art product name'),
      this.translateText(
        product.description,
        sourceLang,
        targetLang,
        'nail art product description',
      ),
      this.translateText(product.seoTitle, sourceLang, targetLang, 'SEO page title for nail product'),
      this.translateText(
        product.seoDescription,
        sourceLang,
        targetLang,
        'SEO meta description for nail product',
      ),
    ]);

    return {
      name: name ?? product.name,
      description,
      seoTitle,
      seoDescription,
    };
  }

  private async translateCollectionFields(
    collection: TranslatableCollectionFields,
    sourceLang: SupportedLocale,
    targetLang: SupportedLocale,
  ) {
    const [name, shortDescription, description, seoTitle, seoDescription] = await Promise.all([
      this.translateText(collection.name, sourceLang, targetLang, 'nail art collection name'),
      this.translateText(
        collection.shortDescription,
        sourceLang,
        targetLang,
        'short description for a nail art collection',
      ),
      this.translateText(
        collection.description,
        sourceLang,
        targetLang,
        'full description for a nail art collection',
      ),
      this.translateText(
        collection.seoTitle,
        sourceLang,
        targetLang,
        'SEO page title for nail collection',
      ),
      this.translateText(
        collection.seoDescription,
        sourceLang,
        targetLang,
        'SEO meta description for nail collection',
      ),
    ]);

    return {
      name: name ?? collection.name,
      shortDescription,
      description,
      seoTitle,
      seoDescription,
    };
  }
}
