import { Inject, Injectable, Logger, Optional } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';

import { I18nTranslationEntity, I18nEntityType } from '@/db/entities/shared/i18n-translation.entity';
import { LanguageDetectionService } from './language-detection.service';
import { SUPPORTED_LOCALES, FALLBACK_LOCALE, TRANSLATION_PROVIDER_TOKEN } from './translation.constants';
import type { SupportedLocale } from './translation.constants';
import type { ITranslationProvider } from './translation.provider.interface';

export interface TranslatableProductFields {
  id: string;
  name: string;
  description?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
}

export interface TranslatableCollectionFields {
  id: string;
  name: string;
  shortDescription?: string | null;
  description?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
}

@Injectable()
export class TranslationService {
  private readonly logger = new Logger(TranslationService.name);

  constructor(
    @InjectRepository(I18nTranslationEntity)
    private readonly repo: Repository<I18nTranslationEntity>,
    private readonly langDetector: LanguageDetectionService,
    @Optional()
    @Inject(TRANSLATION_PROVIDER_TOKEN)
    private readonly provider: ITranslationProvider | null,
  ) {}

  // ─── Generic ─────────────────────────────────────────────────────────────────

  async upsertTranslation(
    entityType: I18nEntityType,
    entityId: string,
    locale: SupportedLocale,
    fields: {
      name?: string | null;
      description?: string | null;
      shortDescription?: string | null;
      seoTitle?: string | null;
      seoDescription?: string | null;
      isAutoGenerated: boolean;
    },
  ): Promise<I18nTranslationEntity> {
    const existing = await this.repo.findOne({ where: { entityType, entityId, locale } });
    if (existing) {
      if (fields.name !== undefined) existing.name = fields.name ?? null;
      if (fields.description !== undefined) existing.description = fields.description ?? null;
      if (fields.shortDescription !== undefined) existing.shortDescription = fields.shortDescription ?? null;
      if (fields.seoTitle !== undefined) existing.seoTitle = fields.seoTitle ?? null;
      if (fields.seoDescription !== undefined) existing.seoDescription = fields.seoDescription ?? null;
      existing.isAutoGenerated = fields.isAutoGenerated;
      return this.repo.save(existing);
    }
    return this.repo.save(
      this.repo.create({
        entityType,
        entityId,
        locale,
        name: fields.name ?? null,
        description: fields.description ?? null,
        shortDescription: fields.shortDescription ?? null,
        seoTitle: fields.seoTitle ?? null,
        seoDescription: fields.seoDescription ?? null,
        isAutoGenerated: fields.isAutoGenerated,
      }),
    );
  }

  async getTranslations(entityType: I18nEntityType, entityId: string): Promise<I18nTranslationEntity[]> {
    return this.repo.find({ where: { entityType, entityId }, order: { locale: 'ASC' } });
  }

  async getBulkTranslations(
    entityType: I18nEntityType,
    entityIds: string[],
  ): Promise<Map<string, I18nTranslationEntity[]>> {
    if (entityIds.length === 0) return new Map();
    const rows = await this.repo
      .createQueryBuilder('t')
      .where('t.entity_type = :entityType', { entityType })
      .andWhere('t.entity_id IN (:...ids)', { ids: entityIds })
      .orderBy('t.entity_id', 'ASC')
      .addOrderBy('t.locale', 'ASC')
      .getMany();

    const map = new Map<string, I18nTranslationEntity[]>();
    for (const row of rows) {
      if (!map.has(row.entityId)) map.set(row.entityId, []);
      map.get(row.entityId)!.push(row);
    }
    return map;
  }

  async getTranslation(
    entityType: I18nEntityType,
    entityId: string,
    locale: SupportedLocale,
  ): Promise<I18nTranslationEntity | null> {
    const tr = await this.repo.findOne({ where: { entityType, entityId, locale } });
    if (tr) return tr;
    if (locale !== FALLBACK_LOCALE) {
      return this.repo.findOne({ where: { entityType, entityId, locale: FALLBACK_LOCALE } });
    }
    return null;
  }

  // ─── Product translations ─────────────────────────────────────────────────────

  async generateForProduct(product: TranslatableProductFields): Promise<void> {
    const sourceLang = this.langDetector.detect(product.name);
    const missingLocales = SUPPORTED_LOCALES.filter((l) => l !== sourceLang);

    await this.upsertProductTranslation(product, sourceLang, {
      name: product.name,
      description: product.description ?? null,
      seoTitle: product.seoTitle ?? null,
      seoDescription: product.seoDescription ?? null,
      isAutoGenerated: false,
    });

    for (const targetLang of missingLocales) {
      try {
        const translated = await this.translateProductFields(product, sourceLang, targetLang);
        await this.upsertProductTranslation(product, targetLang, {
          ...translated,
          isAutoGenerated: true,
        });
      } catch (err) {
        this.logger.error(
          `Failed to generate ${targetLang} translation for product ${product.id}: ${(err as Error).message}`,
        );
      }
    }
  }

  async upsertProductTranslation(
    product: TranslatableProductFields,
    locale: SupportedLocale,
    fields: {
      name: string;
      description: string | null;
      seoTitle: string | null;
      seoDescription: string | null;
      isAutoGenerated: boolean;
    },
  ): Promise<I18nTranslationEntity> {
    return this.upsertTranslation('product', product.id, locale, fields);
  }

  async getProductTranslations(productId: string): Promise<I18nTranslationEntity[]> {
    return this.getTranslations('product', productId);
  }

  async getProductTranslation(
    productId: string,
    locale: SupportedLocale,
  ): Promise<I18nTranslationEntity | null> {
    return this.getTranslation('product', productId, locale);
  }

  // ─── Collection translations ─────────────────────────────────────────────────

  async generateForCollection(collection: TranslatableCollectionFields): Promise<void> {
    const sourceLang = this.langDetector.detect(collection.name);
    const missingLocales = SUPPORTED_LOCALES.filter((l) => l !== sourceLang);

    await this.upsertCollectionTranslation(collection, sourceLang, {
      name: collection.name,
      shortDescription: collection.shortDescription ?? null,
      description: collection.description ?? null,
      seoTitle: collection.seoTitle ?? null,
      seoDescription: collection.seoDescription ?? null,
      isAutoGenerated: false,
    });

    for (const targetLang of missingLocales) {
      try {
        const translated = await this.translateCollectionFields(collection, sourceLang, targetLang);
        await this.upsertCollectionTranslation(collection, targetLang, {
          ...translated,
          isAutoGenerated: true,
        });
      } catch (err) {
        this.logger.error(
          `Failed to generate ${targetLang} translation for collection ${collection.id}: ${(err as Error).message}`,
        );
      }
    }
  }

  async upsertCollectionTranslation(
    collection: TranslatableCollectionFields,
    locale: SupportedLocale,
    fields: {
      name: string;
      shortDescription: string | null;
      description: string | null;
      seoTitle: string | null;
      seoDescription: string | null;
      isAutoGenerated: boolean;
    },
  ): Promise<I18nTranslationEntity> {
    return this.upsertTranslation('collection', collection.id, locale, fields);
  }

  async getCollectionTranslations(collectionId: string): Promise<I18nTranslationEntity[]> {
    return this.getTranslations('collection', collectionId);
  }

  async getCollectionTranslation(
    collectionId: string,
    locale: SupportedLocale,
  ): Promise<I18nTranslationEntity | null> {
    return this.getTranslation('collection', collectionId, locale);
  }

  // ─── Variant translations ─────────────────────────────────────────────────────

  async generateForVariant(variant: { id: string; colorName: string | null }): Promise<void> {
    if (!variant.colorName?.trim()) return;
    const sourceLang = this.langDetector.detect(variant.colorName);
    const missingLocales = SUPPORTED_LOCALES.filter((l) => l !== sourceLang);

    await this.upsertVariantTranslation(variant.id, sourceLang, variant.colorName, false);

    for (const targetLang of missingLocales) {
      try {
        const translated = await this.translateText(
          variant.colorName,
          sourceLang,
          targetLang,
          'nail art supply color name — short, keep proper color names',
        );
        await this.upsertVariantTranslation(variant.id, targetLang, translated ?? variant.colorName, true);
      } catch (err) {
        this.logger.error(
          `Failed to generate ${targetLang} translation for variant ${variant.id}: ${(err as Error).message}`,
        );
      }
    }
  }

  async generateForProductVariants(
    variants: { id: string; colorName: string | null }[],
  ): Promise<void> {
    await Promise.all(
      variants
        .filter((v) => v.colorName?.trim())
        .map((v) => this.generateForVariant(v).catch(() => undefined)),
    );
  }

  async upsertVariantTranslation(
    variantId: string,
    locale: SupportedLocale,
    name: string,
    isAutoGenerated: boolean,
  ): Promise<I18nTranslationEntity> {
    return this.upsertTranslation('product_variant', variantId, locale, { name, isAutoGenerated });
  }

  async loadVariantTranslationsMap(
    variantIds: string[],
    locale: SupportedLocale,
  ): Promise<Map<string, string>> {
    if (variantIds.length === 0) return new Map();

    const rows = await this.repo
      .createQueryBuilder('t')
      .where('t.entity_type = :entityType', { entityType: 'product_variant' })
      .andWhere('t.entity_id IN (:...ids)', { ids: variantIds })
      .andWhere('t.locale IN (:...locales)', {
        locales: locale === FALLBACK_LOCALE ? [locale] : [locale, FALLBACK_LOCALE],
      })
      .getMany();

    const map = new Map<string, string>();
    for (const row of rows) {
      if (row.locale === FALLBACK_LOCALE && row.name) map.set(row.entityId, row.name);
    }
    if (locale !== FALLBACK_LOCALE) {
      for (const row of rows) {
        if (row.locale === locale && row.name) map.set(row.entityId, row.name);
      }
    }
    return map;
  }

  // ─── Utility ─────────────────────────────────────────────────────────────────

  async resolveEnglishName(name: string): Promise<string> {
    const sourceLang = this.langDetector.detect(name);
    if (sourceLang === 'en' || !this.provider?.isAvailable()) return name;
    try {
      const { translatedText } = await this.provider.translate({
        text: name,
        sourceLang,
        targetLang: 'en',
        context: 'product or collection name for URL slug generation — short, keep proper nouns',
      });
      return translatedText || name;
    } catch {
      return name;
    }
  }

  // ─── Private translation helpers ─────────────────────────────────────────────

  async translateText(
    text: string | null | undefined,
    sourceLang: SupportedLocale,
    targetLang: SupportedLocale,
    context: string,
  ): Promise<string | null> {
    if (!text?.trim()) return null;
    if (!this.provider?.isAvailable()) return text;

    const { translatedText } = await this.provider.translate({
      text,
      sourceLang,
      targetLang,
      context,
    });

    return translatedText;
  }

  private async translateProductFields(
    product: TranslatableProductFields,
    sourceLang: SupportedLocale,
    targetLang: SupportedLocale,
  ) {
    const [name, description, seoTitle, seoDescription] = await Promise.all([
      this.translateText(product.name, sourceLang, targetLang, 'nail art product name'),
      this.translateText(product.description, sourceLang, targetLang, 'nail art product description'),
      this.translateText(product.seoTitle, sourceLang, targetLang, 'SEO page title for nail product'),
      this.translateText(product.seoDescription, sourceLang, targetLang, 'SEO meta description for nail product'),
    ]);

    return {
      name: name ?? product.name,
      description,
      seoTitle,
      seoDescription,
    };
  }

  private async translateCollectionFields(
    collection: TranslatableCollectionFields,
    sourceLang: SupportedLocale,
    targetLang: SupportedLocale,
  ) {
    const [name, shortDescription, description, seoTitle, seoDescription] = await Promise.all([
      this.translateText(collection.name, sourceLang, targetLang, 'nail art collection name'),
      this.translateText(collection.shortDescription, sourceLang, targetLang, 'short description for a nail art collection'),
      this.translateText(collection.description, sourceLang, targetLang, 'full description for a nail art collection'),
      this.translateText(collection.seoTitle, sourceLang, targetLang, 'SEO page title for nail collection'),
      this.translateText(collection.seoDescription, sourceLang, targetLang, 'SEO meta description for nail collection'),
    ]);

    return {
      name: name ?? collection.name,
      shortDescription,
      description,
      seoTitle,
      seoDescription,
    };
  }
}
